language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
before_install:
  - sudo add-apt-repository ppa:wnoronha/thrift -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libboost-dev libboost-test-dev
  - sudo apt-get install -qq libboost-program-options-dev libevent-dev libssl-dev
  - sudo apt-get install -qq ruby-dev thrift
before_script:
  - bundle exec bin/id_server &
