language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
before_install:
  - sudo add-apt-repository ppa:wnoronha/thrift -y
  - sudo apt-get update -qq -y
  - sudo apt-get install thrift -qq -y
before_script:
  - bundle exec bin/id_server &
