language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libboost-dev libboost-test-dev
  - sudo apt-get install -qq libboost-program-options-dev libevent-dev libssl-dev
  - sudo apt-get install -qq ruby-dev
  - wget https://dist.apache.org/repos/dist/release/thrift/0.9.0/thrift-0.9.0.tar.gz
  - tar xzf thrift-0.9.0.tar.gz
  - cd thrift-0.9.0
  - ./bootstrap.sh
  - ./configure --disable-gen-erl --disable-gen-hs --without-ruby --without-haskell --without-erlang
  - sudo make install
  - cd ..
before_script:
  - bin/id_server &
