#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'id_service/types'
require 'id_service/client'


module IdService
  class Processor
    include ::Thrift::Processor

    def process_get_id(seqid, iprot, oprot)
      args = read_args(iprot, Get_id_args)
      result = Get_id_result.new()
      result.success = @handler.get_id()
      write_result(result, oprot, 'get_id', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Get_id_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Get_id_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I64, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

